### ISSUE TITLE
Keyboard shortcuts are still mapped to qwerty

### ISSUE THREAD

**Issue by rdoursenaud** [anisse/bepo-android#2]
Shortcuts stays mapped to qwerty.
Is there a way to make them work or are they tied to the keycodes?
They remap correctly using azerty for example, so I believe it's doable.

Thanks for the awesome work by the way!

**Comment by anisse** [comment]
Thanks for taking the time to report this issue.

Can you say which shortcuts you are talking about ? Is it in a given app or system-wide? And which device and Android version are you using ?

**Comment by rdoursenaud** [comment]
Don't know if it's system wide, I only tried my usual shortcuts with Chrome (Address bar: CTRL+L, new tab: CTRL+T, close tab: CTRL+W…).
I use a custom build of CynanogenMod Android 6.0.1 on a Samsung Galaxy Note 2 (GT-N7100) and a Samsung Galaxy Note 10.1 (GT-N8010) with a Lenovo Bluetooth Keyboard (KT-1255).

**Comment by rdoursenaud** [comment]
Just tried CTRL+N (bépo) in Gmail and got the expected result (New mail) but did the same in Drive and it didn't work. Had to use the N key from the qwerty layout.
It seems to vary from application to application… Not cool :(

**Comment by anisse** [comment]
Ok, I understand. In the code, we made choice to expose the keyboard as a "qwerty physical mapping" but with a "bépo software mapping". You can see this here:
https://github.com/anisse/bepo-android/blob/master/clavierexterne/src/main/res/raw/bepo.kcm#L7-L13 . It was intentional because Android doesn't allow a "physically bépo" keyboard.

So apps that are badly written (let's say Chrome), are using the physical mapping, and apps that are correctly written (Gmail) are using the software mapping.

This often happens in software (whatever the OS) written by people who don't even think people might use a different keyboard. You can often see this in flash/browser games for example.

**Comment by anisse** [comment]
Therefore, I'm afraid there's not much that can be done. We could remap the few keys that don't have accents(ÉÀÈÊÇ), but it would just make an inconsistent mapping.

Your best bet would be to open a bug with the Chromium project, because it seems other people are having the issue: https://productforums.google.com/forum/#!topic/docs/5EPjSzDaYj4

**Comment by anisse** [comment]
Weird, it looks like it was fixed recently in Chromium:
https://chromium.googlesource.com/chromium/src.git/+/1da4a34ed8a9fb153dd8924559534ead67d667f6

Can you check on Chrome beta or Canary ?

**Comment by anisse** [comment]
Are you using Chrome >= 47 ?

**Comment by rdoursenaud** [comment]
Thanks for the research. Makes total sense it's an upstream bug.

I'm using Chrome 48. Just tried beta and dev and got same (wrong) behavior.
Inbox also incorrectly behaves.

Guess I'll just have to report upstream bugs and get used to this in the meantime ;)
